In [1]:
#1) loading the data
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

C:\Users\Admin\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
#training set
print(train_images.shape)   # 60000 images with 28x28 pixel
print(train_labels.shape)   # 60000 labels for 60000 images with one to one correspondence
print(train_labels)         # show the class in which the corresponding image fall in. (classes 0-9)

(60000, 28, 28)
(60000,)
[5 0 4 ... 5 6 8]


In [3]:
#test set
print(test_images.shape)   # 10000 images with 28x28 pixel(same image size as the training data)
print(test_labels.shape)
print(test_labels)

(10000, 28, 28)
(10000,)
[7 2 1 ... 4 5 6]


In [4]:
#2) The network architecture
from keras import models
from keras import layers

network = models.Sequential()    #two layered mbodel
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))  #Layers are densely(fully) connected 
                                        #28*28=784    shape of vector in numpy looks like (784,) (notice the comma at the end!)

network.add(layers.Dense(10, activation='softmax'))  #softmax layer, which means it will return an array of 10 probability scores
                                                     #(summing to 1). Each score will be the probability that the current digit 
                                                     #image belongs to one of our 10 digit classes.

In [5]:
#3) compilation
network.compile(optimizer='rmsprop', #optimizer—The mechanism through which the network will update itself based on the data it 
                                     #sees and its loss function.
loss='categorical_crossentropy',     #loss function—How the network will be able to measure its performance on the training data,
                                     #and thus how it will be able to steer itself in the right direction.
metrics=['accuracy'])                #Metrics to monitor during training and testing

In [6]:
#4) Preparing the image data

#grayscale image has value 0-255 where 0 being black and 255 being white
#to get(or convert) the grayscale image pixel to black or white we divide by max(i.e. 255)
train_images = train_images.reshape((60000, 28 * 28))  #reshaping the data according to the input shapeb
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [11]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [7]:
#5) Preparing the labels
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [8]:
#6) training(fitting) the model

network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
60000/60000 [==============================] - 7s 119us/step - loss: 0.2587 - acc: 0.9253
Epoch 2/5
60000/60000 [==============================] - 6s 97us/step - loss: 0.1041 - acc: 0.9688
Epoch 3/5
60000/60000 [==============================] - 5s 91us/step - loss: 0.0687 - acc: 0.9793
Epoch 4/5
60000/60000 [==============================] - 5s 89us/step - loss: 0.0504 - acc: 0.9846
Epoch 5/5
60000/60000 [==============================] - 5s 89us/step - loss: 0.0377 - acc: 0.9887


In [9]:
test_loss, test_acc = network.evaluate(test_images, test_labels)
print('test_acc:', test_acc)

10000/10000 [==============================] - 1s 64us/step
test_acc: 0.9794
